### ISSUE TITLE
Utiliser les filtres et ordres de l'API data.gouv.fr (thèmes et sous-thèmes blocking)

### ISSUE THREAD

**Issue by abulte** [ecolabdata/ecospheres#183]
Following #164 

Utiliser les filtres et ordres de l'API data.gouv.fr afin de basculer la navigation sur la liste des bouquets côté serveur.

**Comment by abulte** [comment]
Probablement pas utile tant que la liste des bouquets tient sur une page ou deux.

Also, les thèmes et sous-thèmes ne sont pas dispo dans l'API data.gouv.fr, on ne peut donc pas tout migrer côté serveur. 

Peut-être envisager de migrer thèmes et sous-thèmes vers des tags ?

**Comment by streino** [comment]
> Probablement pas utile tant que la liste des bouquets tient sur une page ou deux.

Tout à fait d'accord. Ca risque d'augmenter avec la territorialisation, mais tout dépend comment on gère le listing des bouquets territorialisés. 

Le filtre par zone géo peut tout de même être intéressant pour offrir une vue ciblée d'un territoire. Ca reste du nice-to-have à ce stade (edit: [c'est fait](https://github.com/ecolabdata/ecospheres/issues/134)).

Peut-être découper en plusieurs étapes en fonction de l'importance des différents filtres. Et conserver ce ticket pour la mise en place de la mécanique de base (s'il faut la compléter ?). A discuter en hebdo -> [question]

> Peut-être envisager de migrer thèmes et sous-thèmes vers des tags ?

On dupliquerait l'info ou on stocke uniquement dans des tags ? Si 2e option il faudra une convention (= prefix) pour les retrouver. Sauf si on abandonne l'affichage spécial du sous-thème ? cc @martyKN

**Comment by abulte** [comment]
> On dupliquerait l'info ou on stocke uniquement dans des tags ?

Bonne question. J'ai l'intuition qu'on pourrait utiliser uniquement des tags. Le risque principal étant qu'ils soient modifiés par ailleurs, mais je connais pas d'acteur autre que data.gouv.fr via l'admin (et les propriétaires via l'API mais si on part par là...) qui puissent le faire, donc il me semble faible.

Ca pourrait ressembler à :

```
themes:
  id: logement
  label: Se loger
  tag: ecospheres:logement  # or use ecospheres:{id} 
  subthemes:
    - id: construction_renovation
      label: Construction et rénovation des logements
      tag: ecospheres:construction_renovation
```
